// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Cirrious.MvvmCross.Binding.Touch.Views;
using MyHealth.Client.Core.Model;
using Cirrious.MvvmCross.Binding.BindingContext;
using MyHealth.Client.Core;

namespace MyHealth.Client.iOS
{
	public partial class AppointmentTableCell : MvxTableViewCell
	{        
		internal static readonly NSString Identifier = new NSString("AppointmentTableCell");

		public AppointmentTableCell (IntPtr handle) : base (handle)
		{
		}

		public override void LayoutSubviews ()
		{
			base.LayoutSubviews ();

			SetUpUI ();

			SetUpBindings ();
		}

		void SetUpUI ()
		{
			// this.SetUpShadow ();

			CreateRoundCornersOnDoctorPicture ();
		}

		void CreateRoundCornersOnDoctorPicture ()
		{
			pictureFrameView.Layer.CornerRadius = pictureFrameView.Frame.Width / 2;
			doctorImageView.Layer.CornerRadius = doctorImageView.Frame.Width / 2;
		}

		void SetUpBindings ()
		{
			var set = this.CreateBindingSet<AppointmentTableCell, ClinicAppointment>(); 

			set.Bind(doctorImageView)
                .To(vm => vm.Doctor.Picture)
				.WithConversion("InMemoryImage"); 
            
			set.Bind(doctorNameLabel)
                .To(vm => vm.Doctor.Name); 
            
			set.Bind(doctorTitleLabel)
                .To(vm => vm.Doctor.Speciality)
				.WithConversion(new SpecialityIdToStringConverter());
            
			set.Bind(dateLabel)
                .To(vm => vm.DateTime)
				.WithConversion(new DateTimeToMonthDayYearConverter()); 
            
			set.Bind(timeLabel)
                .To(vm => vm.DateTime)
				.WithConversion(new DateTimeToHourMinutesConverter()); 
            
			set.Bind(urgentLabel)
                .For(label => label.Hidden)
                .To(vm => vm.IsUrgent)
				.WithConversion(new NotConverter())
                .WithFallback(true); 

			set.Apply(); 
		}
	}
}
