// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Cirrious.MvvmCross.Binding.Touch.Views;
using MyHealth.Client.Core.Model;
using Cirrious.MvvmCross.Binding.BindingContext;
using MyHealth.Client.Core;
using MyHealth.Client.Core.Converters;
using System.Collections.Generic;

namespace MyHealth.Client.iOS
{
	public partial class TreatmentTableCell : MvxTableViewCell
	{
        internal static readonly NSString Identifier = new NSString("TreatmentTableCell");

		public TreatmentTableCell (IntPtr handle) : base (handle)
		{
		}

        public override void LayoutSubviews ()
        {
            base.LayoutSubviews ();

            SetUpBindings ();
        }

        void SetUpBindings ()
        {
            var set = this.CreateBindingSet<TreatmentTableCell, MedicineWithDoses>(); 

            set.Bind (medecineLabel)
                .To (vm => vm.Medicine)
                .WithConversion (new MedicineToNameWithDosisConverter ());
            set.Bind (hourLabel)
                .To (vm => vm.NextDoseTime)
                .WithConversion (new TimeOfDayToStringConverter ());
            set.Bind(breakfastCountLabel).To(vm => vm.BreakfastDoses);
            set.Bind(lunchCountLabel).To(vm => vm.LunchDoses);
            set.Bind(dinnerCountLabel).To(vm => vm.DinnerDoses);

            set.Apply(); 

            this.AddBindings(new Dictionary<object, string>()
                {
                    { 
                        countdownImageView, 
                        "Image CountDownValueToImageSource(MedicineToCountdown())" 
                    }
                });
        }
	}
}
