// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Cirrious.MvvmCross.Binding.BindingContext;
using MyHealth.Client.Core.ViewModels;
using MyHealth.Client.Core;

namespace MyHealth.Client.iOS
{
    public partial class AppointmentDetailsView : BaseView
	{
        protected AppointmentDetailsViewModel AppointmentDetailsViewModel
        {
            get { return ViewModel as AppointmentDetailsViewModel; }
        }

		public AppointmentDetailsView (IntPtr handle) : base (handle)
		{
            Title = "Detail";
		}

        public override void ViewDidLayoutSubviews ()
        {
            base.ViewDidLayoutSubviews ();

            var paragraphStyle = new NSMutableParagraphStyle { HyphenationFactor = 1 };
            var attributedString = new NSMutableAttributedString(
                AppointmentDetailsViewModel?.Appointment?.Description ?? string.Empty, 
                paragraphStyle: paragraphStyle);

            descriptionLabel.AttributedText = attributedString;
            descriptionLabel.SizeToFit ();
        }

        protected override void SetUpUI ()
        {
            base.SetUpUI ();

            contentView.SetUpShadow();

            pictureFrameView.Layer.CornerRadius = 24;
            doctorImageView.Layer.CornerRadius = 23;
        }

        protected override void SetUpBindings()
        {
            base.SetUpBindings();

            var set = this.CreateBindingSet<AppointmentDetailsView, AppointmentDetailsViewModel>(); 

            set.Bind (doctorImageView)
                .To (vm => vm.Appointment.Doctor.Picture)
                .WithConversion ("InMemoryImage");
            set.Bind (doctorNameLabel)
                .To (vm => vm.Appointment.Doctor.Name);
            set.Bind (doctorSpecialityLabel)
                .To (vm => vm.Appointment.Speciality)
                .WithConversion (new SpecialityIdToStringConverter ());
            set.Bind (urgentLabel)
                .For (label => label.Hidden)
                .To (vm => vm.Appointment.IsUrgent)
                .WithConversion (new NotConverter ())
                .WithFallback(true);
            set.Bind (dateLabel)
                .To (vm => vm.Appointment.DateTime)
                .WithConversion (new DateTimeToMonthDayYearConverter ());
            set.Bind (hourLabel)
                .To (vm => vm.Appointment.DateTime)
                .WithConversion (new DateTimeToHourMinutesConverter ());
            set.Bind (hourIndicatorLabel)
                .To (vm => vm.Appointment.DateTime)
                .WithConversion (new DateTimeToHourIndicatorConverter ());
            set.Bind (roomLabel)
                .To (vm => vm.Appointment.Doctor.CurrentRoomNumber);

            set.Apply();
        }
	}
}
