// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MyHealth.Client.Core.ViewModels;
using Cirrious.MvvmCross.Binding.BindingContext;

namespace MyHealth.Client.iOS
{
    public partial class TreatmentView : BaseView
	{
        static readonly int Margin = 8;

        TreatmentTableViewSource _tableViewSource;

        public TreatmentView (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad()
        {
            _tableViewSource = new TreatmentTableViewSource(treatmentTableView);

            base.ViewDidLoad();

            treatmentTableView.Source = _tableViewSource;
            treatmentTableView.SeparatorStyle = UITableViewCellSeparatorStyle.SingleLine;
            treatmentTableView.SeparatorColor = UIColor.FromRGB(0, 215, 203);
            treatmentTableView.ReloadData();
        }

        protected override void SetUpBindings()
        {
            base.SetUpBindings ();

            var set = this.CreateBindingSet<TreatmentView, TreatmentViewModel>();

            set.Bind(_tableViewSource).To(vm => vm.Treatment);

            set.Apply();
        }

        protected override void SetUpUI ()
        {
            base.SetUpUI ();

            treatmentTableView.ContentInset = new UIEdgeInsets (Margin, 0, Margin, 0);
            treatmentTableView.SeparatorInset = new UIEdgeInsets (Margin, 0, Margin, 0);
        }
	}
}
