// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MyHealth.Client.Core.ViewModels;
using Cirrious.MvvmCross.Binding.BindingContext;
using System.Linq;
using System.Collections.Generic;
using MvvmCross.Plugins.Visibility;

namespace MyHealth.Client.iOS
{
    public partial class UserView : BaseView
	{
		public UserView (IntPtr handle) : base (handle)
		{
		}

        protected override void SetUpUI()
        {
            base.SetUpUI();

            CreateRoundCornersOnDoctorPictures();

            contentView.SetUpShadow();
        }

        protected override void SetUpBindings()
        {
            base.SetUpBindings();

            var set = this.CreateBindingSet<UserView, UserViewModel>();

            set.Bind(userImageView)
                .To(vm => vm.User.Picture)
                .WithConversion("InMemoryImage");
            set.Bind(nameLabel)
                .To(vm => vm.User.Name);
            set.Bind(idLabel)
                .To(vm => vm.User.ClinicId);
			set.Bind (ageBirth)
				.To (vm => vm.User.DateOfBirth)
				.WithConversion ("DateTimeToMonthDayYear");
            set.Bind(genreLabel)
                .To(vm => vm.User.Gender);
            set.Bind(weightLabel)
                .To(vm => vm.User.Weight);
            set.Bind(heightLabel)
                .To(vm => vm.User.Height);
            set.Bind(bloodGroupLabel)
                .To(vm => vm.User.BloodType);
            
            set.Apply();
        }

        void CreateRoundCornersOnDoctorPictures ()
        {
            userFrameView.Layer.CornerRadius = userImageView.Frame.Width / 2;
            userImageView.Layer.CornerRadius = userImageView.Frame.Width / 2;
        }
	}
}
